### ISSUE TITLE
Ashen King summon using the crown causes a crash on servers

### ISSUE THREAD

**Issue by vianZIP** [Jboymercs/end_expansion_final#7]
`[03:22:59] [Server thread/ERROR] [FML]: An Entity type com.example.structure.entity.endking.friendly.EntityFriendKing has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.util.ReportedException: Saving entity NBT
        at net.minecraft.entity.Entity.writeToNBT(Entity.java:1772) ~[vg.class:?]
        at net.minecraft.entity.Entity.writeToNBTOptional(Entity.java:1654) ~[vg.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.writeChunkToNBT(AnvilChunkLoader.java:362) [aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.saveChunk(AnvilChunkLoader.java:174) [aye.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.saveChunkData(ChunkProviderServer.java:202) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.saveChunks(ChunkProviderServer.java:230) [on.class:?]
        at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1007) [oo.class:?]
        at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:408) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:691) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_422]
Caused by: java.lang.NullPointerException
        at com.example.structure.entity.endking.EntityAbstractEndKing.writeEntityToNBT(EntityAbstractEndKing.java:130) ~[EntityAbstractEndKing.class:?]
        at net.minecraft.entity.Entity.writeToNBT(Entity.java:1743) ~[vg.class:?]
        ... 10 more`
can provide more information if needed

**Comment by Jboymercs** [comment]
yes if you could, please give the log or crash report file that has everything. helps with seeing the stacktrace. But thank you for reporting it!

**Comment by Jboymercs** [comment]
This should be fixed within new updates, rewriting states along with a few non-client side checks.
